create database revision;
use revision;
drop table stu;
begin;
create table stu( id int unique auto_increment, name varchar(50), age int);
insert into stu (name,age) values("durgesh",25),("deepu",25),("ruchi",14),("diya",21),("deepika",21);
savepoint sss;
commit;
delete from stu where name="durgesh";
rollback to sss;
update stu set age=59 where name ="durgesh";
select * from stu;
rollback to started;
select distinct  name from stu;
alter table stu add column l_name varchar(50) after name;
update  stu set l_name="rawat" where name="durgesh";
update  stu set l_name="negi" where name="deepu";
update  stu set l_name="rawat" where name="diya";
update  stu set l_name="deepika" where name="bisht";
select concat(name," ",l_name) as fullname from stu;
truncate stu2;
truncate stu;
create table stu2(id int unique auto_increment, st_name varchar(50), abc varchar(50),constraint stu_2 foreign key(id) references stu(id));
show databases;
alter table stu2 change st_name name varchar(50);
alter table stu2 modify  name varchar(60);
select * from stu2;
insert into stu2(st_name,abc) values("durgesh",21),("deepi",21),("san",24);
select * from stu where name like"_iy%";